export type MaterialProperties = {
  moistureBarrier: string;
  oxygenBarrier: string;
  lightBarrier: string;
  gasPermeability: string;
  sealability: string;
  mechanicalStrength: string;
  temperatureSuitability: string;
  moistureRating: number;
  oxygenRating: number;
  lightRating: number;
  strengthRating: number;
  sustainabilityRating: number;
  costRating: number;
  breathable: boolean;
};

export const commoditySeed = [
  { id: "rice", name: "Rice", category: "Cereals", moistureRange: "10–14%", typicalPhRange: "6.0–6.8", respirationClass: "low", oxygenSensitivity: "medium", moistureSensitivity: "high" },
  { id: "wheat", name: "Wheat", category: "Cereals", moistureRange: "10–14%", typicalPhRange: "5.5–6.5", respirationClass: "low", oxygenSensitivity: "medium", moistureSensitivity: "high" },
  { id: "potato", name: "Potato", category: "Vegetables", moistureRange: "75–85%", typicalPhRange: "5.4–6.5", respirationClass: "high", oxygenSensitivity: "medium", moistureSensitivity: "medium" },
  { id: "onion", name: "Onion", category: "Vegetables", moistureRange: "80–90%", typicalPhRange: "5.3–5.8", respirationClass: "medium", oxygenSensitivity: "medium", moistureSensitivity: "medium" },
  { id: "tomato", name: "Tomato", category: "Vegetables", moistureRange: "90–95%", typicalPhRange: "4.0–4.5", respirationClass: "very-high", oxygenSensitivity: "medium", moistureSensitivity: "high" },
  { id: "mango", name: "Mango", category: "Fruits", moistureRange: "80–85%", typicalPhRange: "3.4–4.8", respirationClass: "very-high", oxygenSensitivity: "medium", moistureSensitivity: "high" },
  { id: "apple", name: "Apple", category: "Fruits", moistureRange: "80–86%", typicalPhRange: "3.3–4.0", respirationClass: "medium", oxygenSensitivity: "medium", moistureSensitivity: "medium" },
  { id: "banana", name: "Banana", category: "Fruits", moistureRange: "70–80%", typicalPhRange: "4.5–5.2", respirationClass: "very-high", oxygenSensitivity: "medium", moistureSensitivity: "high" },
  { id: "biscuits", name: "Biscuits", category: "Bakery", moistureRange: "2–6%", typicalPhRange: "6.0–7.0", respirationClass: "low", oxygenSensitivity: "high", moistureSensitivity: "high" },
  { id: "chips", name: "Chips", category: "Snacks", moistureRange: "1–4%", typicalPhRange: "5.5–6.5", respirationClass: "low", oxygenSensitivity: "high", moistureSensitivity: "high" },
  { id: "flour", name: "Flour", category: "Dry Foods", moistureRange: "10–14%", typicalPhRange: "5.5–6.5", respirationClass: "low", oxygenSensitivity: "medium", moistureSensitivity: "high" },
  { id: "pulses", name: "Pulses", category: "Pulses", moistureRange: "8–12%", typicalPhRange: "6.0–7.0", respirationClass: "low", oxygenSensitivity: "medium", moistureSensitivity: "high" },
  { id: "spices", name: "Spices", category: "Spices", moistureRange: "5–12%", typicalPhRange: "5.0–7.0", respirationClass: "low", oxygenSensitivity: "high", moistureSensitivity: "high" },
  { id: "milk-powder", name: "Milk powder", category: "Dairy", moistureRange: "2–5%", typicalPhRange: "6.5–6.8", respirationClass: "low", oxygenSensitivity: "high", moistureSensitivity: "high" },
  { id: "ground-coffee", name: "Ground coffee", category: "Dry Foods", moistureRange: "2–5%", typicalPhRange: "5.0–6.0", respirationClass: "low", oxygenSensitivity: "high", moistureSensitivity: "high" },
  { id: "nuts", name: "Nuts", category: "Dry Foods", moistureRange: "3–8%", typicalPhRange: "5.0–7.0", respirationClass: "low", oxygenSensitivity: "high", moistureSensitivity: "medium" },
  { id: "dry-fruits", name: "Dry fruits", category: "Dry Foods", moistureRange: "10–25%", typicalPhRange: "4.0–6.0", respirationClass: "low", oxygenSensitivity: "high", moistureSensitivity: "high" },
];

export const materialSeed = [
  {
    id: "ldpe",
    name: "LDPE",
    category: "Flexible film",
    polymerFamily: "Polyethylene",
    barrierSummary: "Good moisture barrier; limited oxygen and light barrier",
    sustainability: "Recyclable where film collection exists",
    cost: "low",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Good", oxygenBarrier: "Low", lightBarrier: "Low", gasPermeability: "Relatively permeable", sealability: "Excellent", mechanicalStrength: "Medium", temperatureSuitability: "Ambient to chilled", moistureRating: 4, oxygenRating: 2, lightRating: 1, strengthRating: 3, sustainabilityRating: 2, costRating: 5, breathable: false } satisfies MaterialProperties,
    applications: ["Produce liners", "Dry foods", "General pouches"],
    advantages: ["Easy heat sealing", "Low relative cost", "Flexible"],
    limitations: ["Weak oxygen barrier", "Limited light protection"],
    compatibilityNotes: ["Suitable for many dry and fresh-food secondary structures"],
    thicknessRange: "40–120 µm",
    recyclability: "Potentially recyclable in film streams",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "hdpe",
    name: "HDPE",
    category: "Flexible film",
    polymerFamily: "Polyethylene",
    barrierSummary: "Strong moisture barrier with good stiffness",
    sustainability: "Widely recyclable in rigid formats",
    cost: "low",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Very good", oxygenBarrier: "Low to medium", lightBarrier: "Low", gasPermeability: "Moderately permeable", sealability: "Good", mechanicalStrength: "High", temperatureSuitability: "Ambient to chilled", moistureRating: 5, oxygenRating: 2, lightRating: 1, strengthRating: 4, sustainabilityRating: 3, costRating: 5, breathable: false } satisfies MaterialProperties,
    applications: ["Liners", "Bags", "Rigid containers"],
    advantages: ["High stiffness", "Good moisture protection", "Low cost"],
    limitations: ["Limited oxygen and light barrier"],
    compatibilityNotes: ["Useful where moisture and handling protection dominate"],
    thicknessRange: "40–150 µm",
    recyclability: "Good in established HDPE streams",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "pet",
    name: "PET",
    category: "Film and rigid",
    polymerFamily: "Polyester",
    barrierSummary: "Good stiffness and moderate oxygen barrier",
    sustainability: "Established recyclable stream",
    cost: "medium",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Medium", oxygenBarrier: "Good", lightBarrier: "Medium", gasPermeability: "Moderately resistant", sealability: "Needs sealing layer", mechanicalStrength: "High", temperatureSuitability: "Ambient to chilled", moistureRating: 3, oxygenRating: 4, lightRating: 3, strengthRating: 5, sustainabilityRating: 4, costRating: 3, breathable: false } satisfies MaterialProperties,
    applications: ["Pouches", "Trays", "Bottles"],
    advantages: ["Strong and stiff", "Good print surface", "Recyclable"],
    limitations: ["Usually needs a sealant layer", "Not inherently compostable"],
    compatibilityNotes: ["Works well as an outer layer in multilayer structures"],
    thicknessRange: "12–100 µm",
    recyclability: "Recyclable in PET streams; multilayers vary",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "pp",
    name: "PP",
    category: "Film and rigid",
    polymerFamily: "Polypropylene",
    barrierSummary: "Good moisture resistance and heat performance",
    sustainability: "Recyclable in compatible streams",
    cost: "medium",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Good", oxygenBarrier: "Medium", lightBarrier: "Low", gasPermeability: "Moderately permeable", sealability: "Good", mechanicalStrength: "High", temperatureSuitability: "Ambient to hot-fill depending on grade", moistureRating: 4, oxygenRating: 3, lightRating: 1, strengthRating: 4, sustainabilityRating: 3, costRating: 4, breathable: false } satisfies MaterialProperties,
    applications: ["Trays", "Pouches", "Containers"],
    advantages: ["Good moisture barrier", "Heat resistant", "Good stiffness"],
    limitations: ["Light and oxygen barrier may need enhancement"],
    compatibilityNotes: ["Useful for snacks, dry goods, and many rigid packs"],
    thicknessRange: "20–150 µm",
    recyclability: "Recyclable where PP collection exists",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "bopp",
    name: "BOPP",
    category: "Flexible film",
    polymerFamily: "Polypropylene",
    barrierSummary: "Good stiffness, clarity, and moisture resistance",
    sustainability: "Recyclability depends on structure",
    cost: "medium",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Good", oxygenBarrier: "Medium", lightBarrier: "Low to medium", gasPermeability: "Moderately permeable", sealability: "Needs sealant or coextrusion", mechanicalStrength: "High", temperatureSuitability: "Ambient", moistureRating: 4, oxygenRating: 3, lightRating: 2, strengthRating: 4, sustainabilityRating: 2, costRating: 4, breathable: false } satisfies MaterialProperties,
    applications: ["Snack packs", "Labels", "Overwraps"],
    advantages: ["Clear and printable", "Good stiffness", "Good moisture resistance"],
    limitations: ["Usually needs a sealing layer", "Limited high barrier"],
    compatibilityNotes: ["Strong candidate for dry snacks when oxygen demand is moderate"],
    thicknessRange: "15–60 µm",
    recyclability: "Depends on mono-material construction",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "metallized-pet",
    name: "Metallized PET",
    category: "High-barrier film",
    polymerFamily: "Metallized polyester",
    barrierSummary: "Very strong oxygen, moisture, and light barrier",
    sustainability: "Recycling depends on multilayer structure",
    cost: "medium",
    mapSuitability: "recommended",
    properties: { moistureBarrier: "Very high", oxygenBarrier: "Very high", lightBarrier: "Very high", gasPermeability: "Very low", sealability: "Needs sealant layer", mechanicalStrength: "High", temperatureSuitability: "Ambient", moistureRating: 5, oxygenRating: 5, lightRating: 5, strengthRating: 4, sustainabilityRating: 2, costRating: 3, breathable: false } satisfies MaterialProperties,
    applications: ["Coffee", "Chips", "Spices", "Dry foods"],
    advantages: ["Strong barrier", "Excellent light protection", "Good shelf-life support"],
    limitations: ["Difficult to recycle in multilayers", "Not suitable for respiration-driven produce"],
    compatibilityNotes: ["Use when oxygen, moisture, and light sensitivity are all high"],
    thicknessRange: "50–150 µm structure",
    recyclability: "Structure dependent",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "aluminum-foil-laminate",
    name: "Aluminum foil laminate",
    category: "High-barrier laminate",
    polymerFamily: "Aluminum composite",
    barrierSummary: "Near-total light and gas barrier in a suitable laminate",
    sustainability: "Complex to recycle; high protection trade-off",
    cost: "high",
    mapSuitability: "recommended",
    properties: { moistureBarrier: "Very high", oxygenBarrier: "Very high", lightBarrier: "Very high", gasPermeability: "Very low", sealability: "Good with sealant layer", mechanicalStrength: "High", temperatureSuitability: "Ambient to chilled", moistureRating: 5, oxygenRating: 5, lightRating: 5, strengthRating: 5, sustainabilityRating: 1, costRating: 2, breathable: false } satisfies MaterialProperties,
    applications: ["Milk powder", "Pharmaceutical-like dry foods", "Sensitive spices"],
    advantages: ["Exceptional barrier", "Strong light protection", "Good shelf-life support"],
    limitations: ["Higher cost", "Multilayer recycling challenge"],
    compatibilityNotes: ["Reserve for highly sensitive products or very long targets"],
    thicknessRange: "70–160 µm structure",
    recyclability: "Limited for composite structures",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "paper-based-laminate",
    name: "Paper-based laminate",
    category: "Paper laminate",
    polymerFamily: "Paper composite",
    barrierSummary: "Good printability and tactile quality; barrier depends on coating",
    sustainability: "Paper fraction may be recyclable; structure dependent",
    cost: "medium",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Low to medium", oxygenBarrier: "Low to medium", lightBarrier: "Medium", gasPermeability: "Moderately permeable", sealability: "Good with inner coating", mechanicalStrength: "Medium", temperatureSuitability: "Ambient", moistureRating: 2, oxygenRating: 2, lightRating: 3, strengthRating: 3, sustainabilityRating: 4, costRating: 3, breathable: false } satisfies MaterialProperties,
    applications: ["Dry foods", "Bakery", "Secondary packs"],
    advantages: ["Renewable fiber appearance", "Good printability", "Good consumer feel"],
    limitations: ["Moisture protection is structure-dependent", "May need polymer coating"],
    compatibilityNotes: ["Best where barrier demands are moderate and paper recovery is available"],
    thicknessRange: "60–180 gsm laminate",
    recyclability: "Depends on coating and local systems",
    biodegradability: "Paper fraction can biodegrade",
    compostability: "Structure dependent",
  },
  {
    id: "evoh-multilayer",
    name: "EVOH-containing multilayer",
    category: "High-barrier multilayer",
    polymerFamily: "Ethylene vinyl alcohol",
    barrierSummary: "Excellent oxygen barrier with moisture-sensitive performance",
    sustainability: "Recycling depends on mono-material design",
    cost: "high",
    mapSuitability: "recommended",
    properties: { moistureBarrier: "Good in protected structure", oxygenBarrier: "Very high", lightBarrier: "Low", gasPermeability: "Very low oxygen transmission", sealability: "Good with sealant layer", mechanicalStrength: "High", temperatureSuitability: "Ambient to chilled", moistureRating: 4, oxygenRating: 5, lightRating: 1, strengthRating: 4, sustainabilityRating: 2, costRating: 2, breathable: false } satisfies MaterialProperties,
    applications: ["Oxygen-sensitive foods", "MAP trays", "High-value products"],
    advantages: ["Strong oxygen barrier", "Useful in thermoformed packs", "Good structural options"],
    limitations: ["Moisture can reduce barrier performance", "Higher cost"],
    compatibilityNotes: ["Pair with moisture-resistant outer layers where humidity is high"],
    thicknessRange: "80–250 µm structure",
    recyclability: "Design and collection dependent",
    biodegradability: "Not biodegradable",
    compostability: "Not compostable",
  },
  {
    id: "biodegradable-film",
    name: "Biodegradable film",
    category: "Bio-based film",
    polymerFamily: "Biopolymer blend",
    barrierSummary: "Variable barrier; chosen for end-of-life profile",
    sustainability: "Biodegradability depends on formulation and conditions",
    cost: "high",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Low to medium", oxygenBarrier: "Medium", lightBarrier: "Low", gasPermeability: "Variable", sealability: "Medium", mechanicalStrength: "Medium", temperatureSuitability: "Ambient", moistureRating: 2, oxygenRating: 3, lightRating: 1, strengthRating: 3, sustainabilityRating: 5, costRating: 2, breathable: false } satisfies MaterialProperties,
    applications: ["Short-life dry foods", "Produce wraps", "Trial sustainable formats"],
    advantages: ["Potentially lower persistence", "Can support sustainability goals"],
    limitations: ["Variable barrier and sealability", "Requires supplier validation"],
    compatibilityNotes: ["Validate food contact, shelf life, and end-of-life claims for the exact grade"],
    thicknessRange: "30–120 µm",
    recyclability: "Often not compatible with conventional plastic streams",
    biodegradability: "Formulation dependent",
    compostability: "Not necessarily compostable",
  },
  {
    id: "compostable-film",
    name: "Compostable film",
    category: "Compostable film",
    polymerFamily: "Compostable biopolymer",
    barrierSummary: "Variable barrier with certified compostability target",
    sustainability: "Designed for composting under defined conditions",
    cost: "high",
    mapSuitability: "conditional",
    properties: { moistureBarrier: "Low to medium", oxygenBarrier: "Medium", lightBarrier: "Low", gasPermeability: "Variable", sealability: "Medium", mechanicalStrength: "Medium", temperatureSuitability: "Ambient", moistureRating: 2, oxygenRating: 3, lightRating: 1, strengthRating: 3, sustainabilityRating: 5, costRating: 2, breathable: false } satisfies MaterialProperties,
    applications: ["Short-life dry foods", "Selected produce applications"],
    advantages: ["Can fit composting programs", "Strong sustainability narrative"],
    limitations: ["Requires industrial composting and certification", "Barrier and shelf-life limits"],
    compatibilityNotes: ["Do not assume compostability without certification for the exact structure"],
    thicknessRange: "30–120 µm",
    recyclability: "Usually not recyclable with conventional films",
    biodegradability: "Designed to biodegrade under certified conditions",
    compostability: "Certification and facility dependent",
  },
  {
    id: "breathable-film",
    name: "Breathable film",
    category: "Fresh produce film",
    polymerFamily: "Permeable polymer film",
    barrierSummary: "Designed for controlled gas and moisture exchange",
    sustainability: "Depends on polymer and structure",
    cost: "medium",
    mapSuitability: "recommended",
    properties: { moistureBarrier: "Low to medium", oxygenBarrier: "Low", lightBarrier: "Low", gasPermeability: "High and controlled", sealability: "Good", mechanicalStrength: "Medium", temperatureSuitability: "Chilled", moistureRating: 2, oxygenRating: 1, lightRating: 1, strengthRating: 3, sustainabilityRating: 2, costRating: 3, breathable: true } satisfies MaterialProperties,
    applications: ["Fresh fruits", "Fresh vegetables", "Produce liners"],
    advantages: ["Supports respiration management", "Can reduce condensation risk"],
    limitations: ["Not a high-barrier solution", "Needs commodity-specific validation"],
    compatibilityNotes: ["Use for fresh produce where gas exchange is more important than oxygen exclusion"],
    thicknessRange: "20–80 µm",
    recyclability: "Polymer and local collection dependent",
    biodegradability: "Usually not biodegradable",
    compostability: "Usually not compostable",
  },
  {
    id: "micro-perforated-film",
    name: "Micro-perforated film",
    category: "Fresh produce film",
    polymerFamily: "Perforated polymer film",
    barrierSummary: "Engineered gas exchange through micro-perforations",
    sustainability: "Depends on polymer and structure",
    cost: "medium",
    mapSuitability: "recommended",
    properties: { moistureBarrier: "Low", oxygenBarrier: "Low", lightBarrier: "Low", gasPermeability: "High through perforations", sealability: "Good", mechanicalStrength: "Medium", temperatureSuitability: "Chilled", moistureRating: 1, oxygenRating: 1, lightRating: 1, strengthRating: 3, sustainabilityRating: 2, costRating: 3, breathable: true } satisfies MaterialProperties,
    applications: ["High-respiration produce", "Fresh-cut vegetables", "Leafy greens"],
    advantages: ["Adjustable exchange", "Can reduce anaerobic risk", "Produce-specific"],
    limitations: ["Requires correct perforation design", "Limited moisture barrier"],
    compatibilityNotes: ["Validate perforation size and count against commodity respiration"],
    thicknessRange: "20–80 µm",
    recyclability: "Polymer and local collection dependent",
    biodegradability: "Usually not biodegradable",
    compostability: "Usually not compostable",
  },
];